// <auto-generated />
namespace TrabalhoLocadoraMVC2.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddLocacoesToCliente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLocacoesToCliente));
        
        string IMigrationMetadata.Id
        {
            get { return "201311301745312_AddLocacoesToCliente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
